### PR TITLE
add governance page

### PR DESCRIPTION
**Pull request by troggy**
Resolves https://github.com/leapdao/governance-utilities/issues/13

Reads proposals from Governance contract
Decodes message data with a pinch of human-readable shmoo.

I've left couple of TODOs in the code which should be resolved once #68 is done

### CODE REVIEW

**Comment by sunify** [comment]
1. Reverse order of proposals
2. Add title attribute to shorten addrs

**Comment by troggy** [comment]
@sunify why reverse order of proposals? Right now the next to be applied are shown on top

**Comment by sunify** [comment]
Ignore me then :-)

**Comment by troggy** [comment]
Thanks for the feedback. Addressed the rest of the comments

**Comment by troggy** [comment]
Should I rebase it on top of #71 ?

**Comment by sunify** [comment]
#71 not ready yet

**Pull request merged**
