### PR TITLE
Fix token id for NFTs

### LINKED ISSUE #223: Wallet: Incorrect value is shown for NFT on plasma
image

should be `3434094745039851756550` ([link](https://rinkeby.etherscan.io/token/0xed2903d13584deff039ecd59bb1bec7508f7513b?a=3434094745039851756550))

### LINKED ISSUE #229: Wallet: wrong placeholder for NFT transfer input field
For NFT tokens it should say "Token id to transfer"

image

### PR DESCRIPTION
**Pull request by iamonuwa**
Fixes #229

### CODE REVIEW

**Comment by troggy** [comment]
@iamonuwa maybe fixes #229 ? :)

**Comment by iamonuwa** [comment]
> if you have some NFT of specified color, `AmountInput` component will render a select tag, with several options and blank placeholder:
> image
> 
> Please, refer [Ant Design Documentation for Select](https://ant.design/components/select/) and [AmountInput around line 88](https://github.com/iamonuwa/bridge-ui/blob/cbdc703f865ceba9aeca8426233910154a379423/src/components/amountInput.tsx#L88) to address this issue

I can't reproduce this. Please me know which of the NFTs that does this

**Comment by MaxStalker** [comment]
All of them :)
You just need to have at least 1 token of selected color.

**Comment by iamonuwa** [comment]
> All of them :)
> You just need to have at least 1 token of selected color.

Is this issue reproducible from the /wallet page?

**Comment by MaxStalker** [comment]
This is exactly the place, where I got that screenshot from.

**Comment by iamonuwa** [comment]
> This is exactly the place, where I got that screenshot from.

This is what I see
image

**Comment by MaxStalker** [comment]
VOC is not NFT token.
Try anything below `SDST` token in that dropdown

**Comment by troggy** [comment]
Technically VOC is also NFT (every ERC1948 is NFT afair). However, I think AmountInput renders to select box only for [enumerable](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC721/IERC721Enumerable.sol) NFTs.

So it could be both select or text input for NFTs/NSTs

**Comment by MaxStalker** [comment]
> Technically VOC is also NFT (every ERC1948 is NFT afair)
> 

Pretty sure VOC is ERC20 👇
image

**Comment by iamonuwa** [comment]
@MaxStalker its displayed as NFT.

**Comment by MaxStalker** [comment]
I am a bit confised about what we are discussing 🤪
@iamonuwa can you put a screenshot of the whole page how it renders for you with proposed changes?

**Comment by iamonuwa** [comment]
> I am a bit confised about what we are discussing 🤪
> @iamonuwa can you put a screenshot of the whole page how it renders for you with proposed changes?

Screenshot from 2019-12-16 19-47-07

**Comment by troggy** [comment]
@MaxStalker you are right, ERC20 😅

**Comment by MaxStalker** [comment]
Judging by that screenshot - you've picked *VOC*, which is *ERC20* contract (which you can ensure if you go to [registerToken](https://testnet.leapdao.org/registerToken`) and search for VOC - color 4, ERC20 token. 
That's why input in **Transfer tokens** section have 0 in it.
I've deposited a single **TING** token to your address. 
Now, in order to reproduce the "bug" you will need:
- select a **TING** token from the dropdown next to input in **Make a deposit** section *(I know UI is a bit weird on this)*
- observe that second input (in **Transfer tokens**) section still has empty placeholder, where it should say `Token id to transfer`

**Pull request closed without merging**
